version: 2.1  
description: "An orb to initialize a kubernetes project"
commands:
  install-kubernetes:
    steps:
      - run:
          name: Installing Container Linux Dependencies
          command: |
            sudo apt-get update && sudo apt-get install systemd-sysv

            CNI_VERSION="v0.6.0"
            sudo mkdir -p /opt/cni/bin
            sudo wget -O cni-plugins-amd64-${CNI_VERSION}.tgz "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz"
            sudo mv cni-plugins-amd64-${CNI_VERSION}.tgz /opt/cni/bin/
            cd /opt/cni/bin/
            sudo tar -xvzf /opt/cni/bin/cni-plugins-amd64-${CNI_VERSION}.tgz
            sudo rm -rf cni-plugins-amd64-${CNI_VERSION}.tgz
            cd -

            CRICTL_VERSION="v1.11.1"
            sudo mkdir -p /opt/bin
            sudo chmod +x /opt/bin
            sudo wget -O crictl-${CRICTL_VERSION}-linux-amd64.tar.gz "https://github.com/kubernetes-incubator/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz"
            sudo mv crictl-${CRICTL_VERSION}-linux-amd64.tar.gz /opt/bin/
            cd /opt/bin/
            sudo tar -xvzf crictl-${CRICTL_VERSION}-linux-amd64.tar.gz
            sudo rm -rf crictl-${CRICTL_VERSION}-linux-amd64.tar.gz


            RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"

            sudo curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
            sudo chmod +x {kubeadm,kubelet,kubectl}

            sudo touch /etc/systemd/system/kubelet.service
            sudo chmod -R 777 /etc/systemd/system/kubelet.service
            sudo curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
            sudo chmod -R 444 /etc/systemd/system/kubelet.service

            sudo mkdir -p /etc/systemd/system/kubelet.service.d
            sudo touch /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
            sudo chmod -R 777 /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
            sudo curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/10-kubeadm.conf" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
            sudo chmod -R 444 /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

            sudo systemctl enable kubelet
            sudo systemctl start kubelet

jobs:
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - setup_remote_docker
      - install-kubernetes

